apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.4
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: sqs
            - name: DEFAULT_REGION
              value: eu-west-2
            - name: SQS_ENDPOINT_STRATEGY
              value: path
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 10
            periodSeconds: 5