apiVersion: batch/v1
kind: Job
metadata:
  name: sqs-init
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-localstack
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -sf http://localstack-service:4566/_localstack/health; do
                echo "waiting for localstack..."
                sleep 2
              done
      containers:
        - name: sqs-init
          image: amazon/aws-cli:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
          command:
            - sh
            - -c
            - |
              aws --endpoint-url=http://localstack-service:4566 sqs create-queue --queue-name click-events-dlq &&
              aws --endpoint-url=http://localstack-service:4566 sqs create-queue --queue-name click-events --attributes VisibilityTimeout=30 &&
              echo "queues ready"