apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: devpassword
  DATABASE_URL: postgresql://appuser:devpassword@postgres-service:5432/ecscombined