apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: default
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: ecscombined
  DB_USER: appuser
  SQS_QUEUE_URL: http://localstack-service:4566/000000000000/click-events
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_ENDPOINT_URL: http://localstack-service:4566
  METRICS_PORT: "9091"
  DB_SSL_MODE: disable