name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply-dev:
    name: Apply dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::989346120260:role/ecs-combined-github-actions
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra/environments/dev
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/environments/dev
        run: |
          terraform apply \
            -var="project=ecs-combined" \
            -var="environment=dev" \
            -var="aws_region=eu-west-2" \
            -var="domain=hasanali.uk" \
            -var="certificate_arn=arn:aws:acm:eu-west-2:989346120260:certificate/7268bfb0-315f-46b2-a1ee-08e5407b3394" \
            -auto-approve